---

- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: tap caskroom/versions
      homebrew_tap: tap=caskroom/versions state=present
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - firefox
        - chromium
        - cord
        - libreoffice
        - tunnelblick
        - gimp
        - xquartz
        - inkscape
        - dropbox
        - skype
        - grandperspective
        - vlc
        - moneymoney
        - java7
        - menumeters

  vars:
    - computername: gwaggli
    - git_user_name: Beat Rupp
    - git_user_email: beatrupp@gmail.com
    - osx_defaults:
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'KeyRepeat'
        type: integer
        value: 3
      - domain: 'NSGlobalDomain'
        key: 'InitialKeyRepeat'
        type: integer
        value: 15

   dependencies:
     - roderik.superlumic-vim

